PEEP_THOUGHT_TYPE_CANT_AFFORD_0 = 0       # "I can't afford"
PEEP_THOUGHT_TYPE_SPENT_MONEY = 1         # "I've spent all my money"
PEEP_THOUGHT_TYPE_SICK = 2                # "I feel sick"
PEEP_THOUGHT_TYPE_VERY_SICK = 3           # "I feel very sick"
PEEP_THOUGHT_TYPE_MORE_THRILLING = 4      # "I want to go on something more thrilling than X"
PEEP_THOUGHT_TYPE_INTENSE = 5             # "X looks too intense for me"
PEEP_THOUGHT_TYPE_HAVENT_FINISHED = 6     # "I haven't finished my X yet"
PEEP_THOUGHT_TYPE_SICKENING = 7           # "Just looking at X makes me feel sick"
PEEP_THOUGHT_TYPE_BAD_VALUE = 8           # "I'm not paying that much to go on X"
PEEP_THOUGHT_TYPE_GO_HOME = 9             # "I want to go home"
PEEP_THOUGHT_TYPE_GOOD_VALUE = 10         # "X is really good value"
PEEP_THOUGHT_TYPE_ALREADY_GOT = 11        # "I've already got"
PEEP_THOUGHT_TYPE_CANT_AFFORD = 12        # "I can't afford"
PEEP_THOUGHT_TYPE_NOT_HUNGRY = 13         # "I'm not hungry"
PEEP_THOUGHT_TYPE_NOT_THIRSTY = 14        # "I'm not thirsty"
PEEP_THOUGHT_TYPE_DROWNING = 15           # "Help! I'm drowning!"
PEEP_THOUGHT_TYPE_LOST = 16               # "I'm lost!"
PEEP_THOUGHT_TYPE_WAS_GREAT = 17          # "X was great"
PEEP_THOUGHT_TYPE_QUEUING_AGES = 18       # "I've been queuing for X for ages"
PEEP_THOUGHT_TYPE_TIRED = 19              # "I'm tired"
PEEP_THOUGHT_TYPE_HUNGRY = 20             # "I'm hungry"
PEEP_THOUGHT_TYPE_THIRSTY = 21            # "I'm thirsty"
PEEP_THOUGHT_TYPE_TOILET = 22             # "I need to go to the toilet"
PEEP_THOUGHT_TYPE_CANT_FIND = 23          # "I can't find X"
PEEP_THOUGHT_TYPE_NOT_PAYING = 24         # "I'm not paying that much to use X"
PEEP_THOUGHT_TYPE_NOT_WHILE_RAINING = 25  # "I'm not going on X while it's raining"
PEEP_THOUGHT_TYPE_BAD_LITTER = 26         # "The litter here is really bad"
PEEP_THOUGHT_TYPE_CANT_FIND_EXIT = 27     # "I can't find the exit"
PEEP_THOUGHT_TYPE_GET_OFF = 28            # "I want to get off X"
PEEP_THOUGHT_TYPE_GET_OUT = 29            # "I want to get out of X"
PEEP_THOUGHT_TYPE_NOT_SAFE = 30           # "I'm not going on X - it isn't safe"
PEEP_THOUGHT_TYPE_PATH_DISGUSTING = 31    # "This path is disgusting"
PEEP_THOUGHT_TYPE_CROWDED = 32            # "It's too crowded here"
PEEP_THOUGHT_TYPE_VANDALISM = 33          # "The vandalism here is really bad"
PEEP_THOUGHT_TYPE_SCENERY = 34            # "Great scenery!"
PEEP_THOUGHT_TYPE_VERY_CLEAN = 35         # "This park is very clean and tidy"
PEEP_THOUGHT_TYPE_FOUNTAINS = 36          # "The jumping fountains are great"
PEEP_THOUGHT_TYPE_MUSIC = 37              # "The music is nice here"
PEEP_THOUGHT_TYPE_BALLOON = 38            # "This balloon from X is really good value"
PEEP_THOUGHT_TYPE_TOY = 39                # "This cuddly toy from X is really good value"
PEEP_THOUGHT_TYPE_MAP = 40 
PEEP_THOUGHT_TYPE_PHOTO = 41              # "This on ride photo from X is really good value"
PEEP_THOUGHT_TYPE_UMBRELLA = 42 
PEEP_THOUGHT_TYPE_DRINK = 43 
PEEP_THOUGHT_TYPE_BURGER = 44 
PEEP_THOUGHT_TYPE_CHIPS = 45 
PEEP_THOUGHT_TYPE_ICE_CREAM = 46 
PEEP_THOUGHT_TYPE_CANDYFLOSS = 47 

PEEP_THOUGHT_TYPE_PIZZA = 51 

PEEP_THOUGHT_TYPE_POPCORN = 53 
PEEP_THOUGHT_TYPE_HOT_DOG = 54 
PEEP_THOUGHT_TYPE_TENTACLE = 55 
PEEP_THOUGHT_TYPE_HAT = 56 
PEEP_THOUGHT_TYPE_TOFFEE_APPLE = 57 
PEEP_THOUGHT_TYPE_TSHIRT = 58 
PEEP_THOUGHT_TYPE_DOUGHNUT = 59 
PEEP_THOUGHT_TYPE_COFFEE = 60 

PEEP_THOUGHT_TYPE_CHICKEN = 62 
PEEP_THOUGHT_TYPE_LEMONADE = 63 

PEEP_THOUGHT_TYPE_WOW = 67              # "Wow!"

PEEP_THOUGHT_TYPE_WOW2 = 70             # "Wow!"
PEEP_THOUGHT_TYPE_WATCHED = 71          # "I have the strangest feeling someone is watching me"
PEEP_THOUGHT_TYPE_BALLOON_MUCH = 72     # "I'm not paying that much to get a balloon from X"
PEEP_THOUGHT_TYPE_TOY_MUCH = 73 
PEEP_THOUGHT_TYPE_MAP_MUCH = 74 
PEEP_THOUGHT_TYPE_PHOTO_MUCH = 75 
PEEP_THOUGHT_TYPE_UMBRELLA_MUCH = 76 
PEEP_THOUGHT_TYPE_DRINK_MUCH = 77 
PEEP_THOUGHT_TYPE_BURGER_MUCH = 78 
PEEP_THOUGHT_TYPE_CHIPS_MUCH = 79 
PEEP_THOUGHT_TYPE_ICE_CREAM_MUCH = 80 
PEEP_THOUGHT_TYPE_CANDYFLOSS_MUCH = 81 

PEEP_THOUGHT_TYPE_PIZZA_MUCH = 85 

PEEP_THOUGHT_TYPE_POPCORN_MUCH = 87 
PEEP_THOUGHT_TYPE_HOT_DOG_MUCH = 88 
PEEP_THOUGHT_TYPE_TENTACLE_MUCH = 89 
PEEP_THOUGHT_TYPE_HAT_MUCH = 90 
PEEP_THOUGHT_TYPE_TOFFEE_APPLE_MUCH = 91 
PEEP_THOUGHT_TYPE_TSHIRT_MUCH = 92 
PEEP_THOUGHT_TYPE_DOUGHNUT_MUCH = 93 
PEEP_THOUGHT_TYPE_COFFEE_MUCH = 94 

PEEP_THOUGHT_TYPE_CHICKEN_MUCH = 96 
PEEP_THOUGHT_TYPE_LEMONADE_MUCH = 97 

PEEP_THOUGHT_TYPE_PHOTO2 = 104  # "This on-ride photo from X is really good value"
PEEP_THOUGHT_TYPE_PHOTO3 = 105 
PEEP_THOUGHT_TYPE_PHOTO4 = 106 
PEEP_THOUGHT_TYPE_PRETZEL = 107 
PEEP_THOUGHT_TYPE_HOT_CHOCOLATE = 108 
PEEP_THOUGHT_TYPE_ICED_TEA = 109 
PEEP_THOUGHT_TYPE_FUNNEL_CAKE = 110 
PEEP_THOUGHT_TYPE_SUNGLASSES = 111 
PEEP_THOUGHT_TYPE_BEEF_NOODLES = 112 
PEEP_THOUGHT_TYPE_FRIED_RICE_NOODLES = 113 
PEEP_THOUGHT_TYPE_WONTON_SOUP = 114 
PEEP_THOUGHT_TYPE_MEATBALL_SOUP = 115 
PEEP_THOUGHT_TYPE_FRUIT_JUICE = 116 
PEEP_THOUGHT_TYPE_SOYBEAN_MILK = 117 
PEEP_THOUGHT_TYPE_SU_JONGKWA = 118 
PEEP_THOUGHT_TYPE_SUB_SANDWICH = 119 
PEEP_THOUGHT_TYPE_COOKIE = 120 

PEEP_THOUGHT_TYPE_ROAST_SAUSAGE = 124 

PEEP_THOUGHT_TYPE_PHOTO2_MUCH = 136 
PEEP_THOUGHT_TYPE_PHOTO3_MUCH = 137 
PEEP_THOUGHT_TYPE_PHOTO4_MUCH = 138 
PEEP_THOUGHT_TYPE_PRETZEL_MUCH = 139 
PEEP_THOUGHT_TYPE_HOT_CHOCOLATE_MUCH = 140 
PEEP_THOUGHT_TYPE_ICED_TEA_MUCH = 141 
PEEP_THOUGHT_TYPE_FUNNEL_CAKE_MUCH = 142 
PEEP_THOUGHT_TYPE_SUNGLASSES_MUCH = 143 
PEEP_THOUGHT_TYPE_BEEF_NOODLES_MUCH = 144 
PEEP_THOUGHT_TYPE_FRIED_RICE_NOODLES_MUCH = 145 
PEEP_THOUGHT_TYPE_WONTON_SOUP_MUCH = 146 
PEEP_THOUGHT_TYPE_MEATBALL_SOUP_MUCH = 147 
PEEP_THOUGHT_TYPE_FRUIT_JUICE_MUCH = 148 
PEEP_THOUGHT_TYPE_SOYBEAN_MILK_MUCH = 149 
PEEP_THOUGHT_TYPE_SU_JONGKWA_MUCH = 150 
PEEP_THOUGHT_TYPE_SUB_SANDWICH_MUCH = 151 
PEEP_THOUGHT_TYPE_COOKIE_MUCH = 152 

PEEP_THOUGHT_TYPE_ROAST_SAUSAGE_MUCH = 156 

PEEP_THOUGHT_TYPE_HELP = 168                  # "Help! Put me down!"
PEEP_THOUGHT_TYPE_RUNNING_OUT = 169           # "I'm running out of cash!"
PEEP_THOUGHT_TYPE_NEW_RIDE = 170              # "Wow! A new ride being built!"
PEEP_THOUGHT_TYPE_NICE_RIDE_DEPRECATED = 171  # "Nice ride! But not as good as the Phoenix..."
PEEP_THOUGHT_TYPE_EXCITED_DEPRECATED = 172    # "I'm so excited - It's an Intamin ride!"
PEEP_THOUGHT_TYPE_HERE_WE_ARE = 173           # "...and here we are on X!"

PEEP_THOUGHT_TYPE_NONE = 255


crowded_thoughts = [
    PEEP_THOUGHT_TYPE_LOST,  
    PEEP_THOUGHT_TYPE_TIRED, 
    PEEP_THOUGHT_TYPE_BAD_LITTER, 
    PEEP_THOUGHT_TYPE_HUNGRY, 
    PEEP_THOUGHT_TYPE_THIRSTY, 
    PEEP_THOUGHT_TYPE_VERY_CLEAN, 
    PEEP_THOUGHT_TYPE_CROWDED, 
    PEEP_THOUGHT_TYPE_SCENERY, 
    PEEP_THOUGHT_TYPE_VERY_CLEAN, 
    PEEP_THOUGHT_TYPE_MUSIC, 
    PEEP_THOUGHT_TYPE_WATCHED, 
    PEEP_THOUGHT_TYPE_NOT_HUNGRY, 
    PEEP_THOUGHT_TYPE_NOT_THIRSTY, 
    PEEP_THOUGHT_TYPE_TOILET, 
    PEEP_THOUGHT_TYPE_NONE, 
    PEEP_THOUGHT_TYPE_NONE, 
]

PEEP_THOUGHT_ITEM_NONE = 255

# ItemStandardFlags
PEEP_ITEM_BALLOON = (1 << 0) 
PEEP_ITEM_TOY = (1 << 1) 
PEEP_ITEM_MAP = (1 << 2) 
PEEP_ITEM_PHOTO = (1 << 3) 
PEEP_ITEM_UMBRELLA = (1 << 4) 
PEEP_ITEM_DRINK = (1 << 5) 
PEEP_ITEM_BURGER = (1 << 6) 
PEEP_ITEM_CHIPS = (1 << 7) 
PEEP_ITEM_ICE_CREAM = (1 << 8) 
PEEP_ITEM_CANDYFLOSS = (1 << 9) 
PEEP_ITEM_EMPTY_CAN = (1 << 10) 
PEEP_ITEM_RUBBISH = (1 << 11) 
PEEP_ITEM_EMPTY_BURGER_BOX = (1 << 12) 
PEEP_ITEM_PIZZA = (1 << 13) 
PEEP_ITEM_VOUCHER = (1 << 14) 
PEEP_ITEM_POPCORN = (1 << 15) 
PEEP_ITEM_HOT_DOG = (1 << 16) 
PEEP_ITEM_TENTACLE = (1 << 17) 
PEEP_ITEM_HAT = (1 << 18) 
PEEP_ITEM_TOFFEE_APPLE = (1 << 19) 
PEEP_ITEM_TSHIRT = (1 << 20) 
PEEP_ITEM_DOUGHNUT = (1 << 21) 
PEEP_ITEM_COFFEE = (1 << 22) 
PEEP_ITEM_EMPTY_CUP = (1 << 23) 
PEEP_ITEM_CHICKEN = (1 << 24) 
PEEP_ITEM_LEMONADE = (1 << 25) 
PEEP_ITEM_EMPTY_BOX = (1 << 26) 
PEEP_ITEM_EMPTY_BOTTLE = (1 << 27) 

#ItemExtraFlags
PEEP_ITEM_PHOTO2 = (1 << 0) 
PEEP_ITEM_PHOTO3 = (1 << 1) 
PEEP_ITEM_PHOTO4 = (1 << 2) 
PEEP_ITEM_PRETZEL = (1 << 3) 
PEEP_ITEM_CHOCOLATE = (1 << 4) 
PEEP_ITEM_ICED_TEA = (1 << 5) 
PEEP_ITEM_FUNNEL_CAKE = (1 << 6) 
PEEP_ITEM_SUNGLASSES = (1 << 7) 
PEEP_ITEM_BEEF_NOODLES = (1 << 8) 
PEEP_ITEM_FRIED_RICE_NOODLES = (1 << 9) 
PEEP_ITEM_WONTON_SOUP = (1 << 10) 
PEEP_ITEM_MEATBALL_SOUP = (1 << 11) 
PEEP_ITEM_FRUIT_JUICE = (1 << 12) 
PEEP_ITEM_SOYBEAN_MILK = (1 << 13) 
PEEP_ITEM_SU_JONGKWA = (1 << 14) 
PEEP_ITEM_SUB_SANDWICH = (1 << 15) 
PEEP_ITEM_COOKIE = (1 << 16) 
PEEP_ITEM_EMPTY_BOWL_RED = (1 << 17) 
PEEP_ITEM_EMPTY_DRINK_CARTON = (1 << 18) 
PEEP_ITEM_EMPTY_JUICE_CUP = (1 << 19) 
PEEP_ITEM_ROAST_SAUSAGE = (1 << 20) 
xPEEP_ITEM_EMPTY_BOWL_BLUE = (1 << 21) 