general:
    render: False
    verbose: False
    render_screen_width: 500
    render_screen_height: 500
parallelism:
    enabled: True
    threads: 3
environment:
    n_guests: 20
    map_width: 30
    map_height: 30
    n_actions: 10
    ride_range: [3, 8]
    fixed_path: True # all ride placements along fixed square path
experiments:
    ticks: [500]
evolution:
    population_size: 10
    max_mutate_builds: 10
    fitness_type: 2
    eval_ticks: 50
    gen_count: 10
    save_path: results/test5-nausea-changed/
    action: evolve
    dimensions: 
        keys:
            x: happiness
            y: ride_count
        skip:
            x: 5
            y: 1
    cell_pop_size: 3
    elite_prob: 0.5
    mutation_prob: 1.0
    print_map: False
    checkpoint:
        initialize_enabled: False
        elite_path: results/9.p
        save_nth_epoch: 3
