general:
    render: False
    verbose: False
    render_screen_width: 500
    render_screen_height: 500
parallelism:
    enabled: True
    threads: 4
environment:
    n_guests: 100
    map_width: 30
    map_height: 30
    n_actions: 10
experiments:
    ticks: [500]
evolution:
    population_size: 100
    max_mutate_builds: 10
    mutation_prob: 1.0
    dimension_keys: [ride_count]
    fitness_type: 2
    ride_range: [3, 8]
    eval_ticks: 500
    gen_count: 5
