general:
    render: False
    verbose: False
environment:
    n_guests: 100
    map_width: 50
    map_height: 50
    n_actions: 10
experiments:
    ticks: [500]

evolution:
    population_size: 100
    mutation:
        add_prob: 0.3
        delete_prob: 0.1
        move_prob: 0.4
    dimension_keys: [ride_count]
    fitness_type: 1
