general:
    render: True
    verbose: False
    render_screen_width: 500
    render_screen_height: 500
parallelism:
    enabled: True
    threads: 4
environment:
    n_guests: 100
    map_width: 30
    map_height: 30
    n_actions: 10
    ride_range: [3, 8]
    fixed_path: True # all ride placements along fixed square path
experiments:
    ticks: [500]
evolution:
    population_size: 10
    max_mutate_builds: 10
    mutation_prob: 1.0
    dimension_keys: [ride_count]
    fitness_type: 2
    eval_ticks: 250
    gen_count: 5
    save_path: results/
    action: evolve
