general:
    render: False
    verbose: False
    render_screen_width: 500
    render_screen_height: 500
parallelism:
    enabled: True
    threads: 3
environment:
    n_guests: 20
    map_width: 30
    map_height: 30
    n_actions: 10
    ride_range: [0, 4]
    fixed_path: True  # all ride placements along fixed square path
    ride_cost: False  # whether or not rides cost money to build
    init_money: 15000  # how much money the park starts out with
    deletion_rate: 2  # how many deletion actions (at present, there are 26 ride-placement actions -- one per ride type -- so "26" means 50/50 build/deletion rates)
experiments:
    ticks: [500]
evolution:
    population_size: 100
    max_mutate_builds: 10
    fitness_type: 2
    eval_ticks: 1000
    gen_count: 10000
    save_path: results/
    action: evolve
    dimensions: 
        keys:
            x: happiness
            y: ride_count
        skip:
            x: 10
            y: 1
    cell_pop_size: 3
    elite_prob: 0.5
    replace_prob: 0.2
    mutation_prob: 1.0
    print_map: False
    checkpoint:
        initialize_enabled: False
        elite_path: results/9.p
        save_nth_epoch: 2500
